# netty配置
netty:
  tcp:
    port: 5001
  # bossGroup的线程数
  boss:
    thread:
      count: 2
  # worker的线程数
  worker:
    thread:
      count: 12
  # client的线程数
  client:
    thread:
      count: 12
  # 是否使用长链接
  so:
    keepalive: true
    backlog: 100
